
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfgqmwrgraenvnhidpvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmZ3Ftd3JncmFlbnZuaGlkcHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDk4MTgsImV4cCI6MjA1OTMyNTgxOH0.kknmKj_W_xNudlEuvknuZmXi8vXv4U2GL40xZRCtaEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
